#!/bin/sh
set -e

escape_js() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

RAG_API_URL_ESCAPED="$(escape_js "${VITE_RAG_API_URL:-}")"
RAG_TOKEN_ESCAPED="$(escape_js "${VITE_RAG_TOKEN:-}")"
APPINSIGHTS_CONNECTION_STRING_ESCAPED="$(escape_js "${VITE_APPLICATIONINSIGHTS_CONNECTION_STRING:-}")"
APPINSIGHTS_CLOUD_ROLE_NAME_ESCAPED="$(escape_js "${VITE_APPINSIGHTS_CLOUD_ROLE_NAME:-anita-frontend}")"
APPINSIGHTS_ENABLED_ESCAPED="$(escape_js "${VITE_APPINSIGHTS_ENABLED:-true}")"

cat >/usr/share/nginx/html/env-config.js <<EOF
window.__RUNTIME_CONFIG__ = {
  VITE_RAG_API_URL: "${RAG_API_URL_ESCAPED}",
  VITE_RAG_TOKEN: "${RAG_TOKEN_ESCAPED}",
  VITE_APPLICATIONINSIGHTS_CONNECTION_STRING: "${APPINSIGHTS_CONNECTION_STRING_ESCAPED}",
  VITE_APPINSIGHTS_CLOUD_ROLE_NAME: "${APPINSIGHTS_CLOUD_ROLE_NAME_ESCAPED}",
  VITE_APPINSIGHTS_ENABLED: "${APPINSIGHTS_ENABLED_ESCAPED}"
};
EOF

exec nginx -g 'daemon off;'
